### ISSUE TITLE
Design device collection schema and device model

### ISSUE THREAD

**Issue by chiro-hiro** [DenoteMD/denote-md-backend#50]
We need to add new Mongoose schema and Model to start implementing multi-devices login.

Device identity  could be consider to be store in our MongoDB following fields:

- IP Address
- Device name or user-agent
- Device uuid
- Last active
- Login time

**Comment by trinhlaosu** [comment]
Design based on dbdiagram:
https://dbdiagram.io/d/5f26caf27543d301bf5d927a
=>So, there isn't field Login Time
